spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.19/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.19
    port: 6379



server:
  context-path: /sell


wechat:
  mpAppId: wx909701d6c726456e
  mpAppSecret: d0a756ad4a28f4aaa8aac821a8443b0e
  openAppId: 123123123
  openAppSecret: 123123123
  mchId: 12345667899
  mchKey: 123456
  keyPath: /local/h5.p12
  notifyUrl: http://gongjunrui.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: d-959zURuPoqXTJrEx6faLNMaYIdupJfaK7LFfjaTgc


projectUrl:
  wechatMpAuthorize: http://gongjunrui.natapp1.cc
  wechatOpenAuthorize: http://gongjunrui.natapp1.cc
  sell: http://gongjunrui.natapp1.cc



#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level: debug
